Importing the Dependencies

In [116]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Collection and Pre-Processing

In [117]:
# Loading the data from csv file to a Pandas Dataframe
raw_mail_data = pd.read_csv(r'C:\Users\Vikram\OneDrive\Desktop\ML Projects\Projects\17.1. Mail dataset.csv')

In [118]:
# First 5 rows of the dataset
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [119]:
# Replace the null values with a null string
mail_data = raw_mail_data.where((pd.notnull(raw_mail_data)), '')

In [120]:
# First 5 rows of the dataframe
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [121]:
# Checking the number of rows and columns in the dataframe
mail_data.shape

(5572, 2)

Label Encoding

In [122]:
# Label spam mail as 0, and ham mail as 1
mail_data = mail_data.replace({'Category': {'spam':0, 'ham':1}}, inplace=True)

In [123]:
# Separating the data as text and label
X = mail_data['Message']  # text
Y = mail_data['Category']  # label

Splitting the data into Training data and Test data

In [124]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [125]:
print(X.shape, X_train.shape, X_test.shape)

(5572,) (4457,) (1115,)

Feature Extraction

In [126]:
# Transform the text data to feature vectors that can be used as input to the Logistic Regression
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

# Convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [127]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34768 stored elements and shape (4457, 7458)>
  Coords	Values
  (0, 6927)	0.48935591439341625
  (0, 6586)	0.44333254982109394
  (0, 3958)	0.6161071828926097
  (0, 4334)	0.42941702167641554
  (1, 3168)	0.5869421390016224
  (1, 6971)	0.4281243465155688
  (1, 1428)	0.5869421390016224
  (1, 2121)	0.35736171430221464
  (2, 6878)	0.35749230587184955
  (2, 1876)	0.28751725124107325
  (2, 5894)	0.35749230587184955
  (2, 806)	0.26730249393705324
  (2, 5695)	0.35749230587184955
  (2, 4884)	0.35749230587184955
  (2, 3852)	0.3408491178137899
  (2, 7353)	0.31988118061968496
  (2, 5115)	0.3408491178137899
  (3, 1876)	0.3080768784015236
  (3, 7297)	0.22192369472149484
  (3, 7000)	0.30072945056088285
  (3, 7065)	0.32795623716393424
  (3, 2060)	0.24915048132454623
  (3, 5005)	0.3169028431039865
  (3, 7248)	0.23571908490908416
  (3, 300)	0.2915969875465198
  :	:
  (4454, 4627)	0.3831814754124698
  (4454, 311)	0.19547195974237946
  (4454, 5068)	0.22284357632450164
  (4454, 1094)	0.24862733340971144
  (4454, 1575)	0.20946314330145205
  (4454, 666)	0.28653660324238944
  (4454, 2244)	0.2526916142542512
  (4454, 7084)	0.2689097965804433
  (4454, 571)	0.3005277868014621
  (4454, 5077)	0.3005277868014621
  (4454, 297)	0.3005277868014621
  (4455, 3084)	0.3019392955127119
  (4455, 4614)	0.4677148905542796
  (4455, 3701)	0.546620099025937
  (4455, 7075)	0.6255253074975946
  (4456, 6575)	0.15362974460832007
  (4456, 5820)	0.18767970267638426
  (4456, 7376)	0.20404881687716278
  (4456, 7033)	0.43304344994724825
  (4456, 380)	0.24893867331233713
  (4456, 2509)	0.20620887737471993
  (4456, 7032)	0.2868954144677231
  (4456, 909)	0.26924653489772427
  (4456, 5009)	0.6018082365591317
  (4456, 3768)	0.30090411827956587

Training the Model

Logistic Regression

In [128]:
# Loading the model
model = LogisticRegression()

In [129]:
# Training the model with the Training data
model.fit(X_train_features, Y_train)

LogisticRegression()

Evaluating the trained model

In [130]:
# Prediction on Training data
prediction_on_training_data = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train, prediction_on_training_data)

In [131]:
print(f'Accuracy on Training data : {accuracy_on_training_data}')

Accuracy on Training data : 0.9685887368184878

In [132]:
# Prediction on Test data
prediction_on_test_data = model.predict(X_test_features)
accuracy_on_test_data = accuracy_score(Y_test, prediction_on_test_data)

In [133]:
print(f'Accuracy on Test data : {accuracy_on_test_data}')

Accuracy on Test data : 0.9533632286995516

Building a Predictive System

In [134]:
input_mail = ["WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only."]

# Convert text to feature vectors
input_data_features = feature_extraction.transform(input_mail)

# Making predictions
prediction = model.predict(input_data_features)
print(prediction)

[0]

In [135]:
if prediction[0] == 0:
    print('This is a spam mail.')
else:
    print('This is a ham mail.')

This is a spam mail.